/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JDesktopPane;

/**
 *
 * @author Manuel Trejos
 */
public class JFInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form JFInterfaz
     */
    public JFInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdp = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmRegistrar = new javax.swing.JMenu();
        jmiRegPersonas = new javax.swing.JMenuItem();
        jmVisualizar = new javax.swing.JMenu();
        jmiVisPersonas = new javax.swing.JMenuItem();
        jmActualizar = new javax.swing.JMenu();
        jmiActPersona = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpLayout = new javax.swing.GroupLayout(jdp);
        jdp.setLayout(jdpLayout);
        jdpLayout.setHorizontalGroup(
            jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdpLayout.setVerticalGroup(
            jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jmRegistrar.setText("Registrar");

        jmiRegPersonas.setText("Personas");
        jmiRegPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegPersonasActionPerformed(evt);
            }
        });
        jmRegistrar.add(jmiRegPersonas);

        jMenuBar1.add(jmRegistrar);

        jmVisualizar.setText("Visualizar");

        jmiVisPersonas.setText("Personas");
        jmiVisPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVisPersonasActionPerformed(evt);
            }
        });
        jmVisualizar.add(jmiVisPersonas);

        jMenuBar1.add(jmVisualizar);

        jmActualizar.setText("Actualizar");

        jmiActPersona.setText("Persona");
        jmiActPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiActPersonaActionPerformed(evt);
            }
        });
        jmActualizar.add(jmiActPersona);

        jMenuBar1.add(jmActualizar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiRegPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegPersonasActionPerformed
        JIFRegistrarPersona jifRegPer = new JIFRegistrarPersona();
        this.jdp.add(jifRegPer);
        jifRegPer.setVisible(true);
       
    }//GEN-LAST:event_jmiRegPersonasActionPerformed

    private void jmiVisPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVisPersonasActionPerformed
        JIFMostrarPersonas jifMostrarP = new JIFMostrarPersonas();
        this.jdp.add(jifMostrarP);
        jifMostrarP.setVisible(true);
    }//GEN-LAST:event_jmiVisPersonasActionPerformed

    private void jmiActPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiActPersonaActionPerformed
        JIFPersonToUpdate jifPtU = new JIFPersonToUpdate(this);
        this.jdp.add(jifPtU);
        jifPtU.setVisible(true);
    }//GEN-LAST:event_jmiActPersonaActionPerformed

    public JDesktopPane getJdp() {
        return jdp;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdp;
    private javax.swing.JMenu jmActualizar;
    private javax.swing.JMenu jmRegistrar;
    private javax.swing.JMenu jmVisualizar;
    private javax.swing.JMenuItem jmiActPersona;
    private javax.swing.JMenuItem jmiRegPersonas;
    private javax.swing.JMenuItem jmiVisPersonas;
    // End of variables declaration//GEN-END:variables
}
