/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Business.PersonaBusiness;
import Domain.Persona;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manuel Trejos
 */
public class JIFMostrarPersonas extends javax.swing.JInternalFrame {

    private DefaultTableModel dtmPersonas;

    public JIFMostrarPersonas() {
        initComponents();
        this.dtmPersonas = new DefaultTableModel();
        cargarDatos();
        this.jTable1.setModel(this.dtmPersonas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 153, 153));
        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de personas");
        setToolTipText("");

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        try {
            this.dtmPersonas.addColumn("Nombre");
            this.dtmPersonas.addColumn("ID");
            this.dtmPersonas.addColumn("Fecha de Inicio");
            PersonaBusiness pb = new PersonaBusiness();
            ArrayList<Persona> personas = pb.devolverPersonas();
            for (int i = 0; i < personas.size(); i++) {
                this.dtmPersonas.addRow(new String[]{
                    personas.get(i).getNombre(),
                    personas.get(i).getID(),
                    personas.get(i).getFechaInicioLab()
                });
            }
        } //cargarDatos
        catch (IOException ex) {
            Logger.getLogger(JIFMostrarPersonas.class.getName()).log(Level.SEVERE, null, ex);
        }
    } //cargarDatos
} //class
